publish_to: none

name: domain
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # Add local dependencies here.
  common:
    path: ../common
  data:
    path: ../data

  # Add 3rd party dependencies here as needed.
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.6.0
  freezed: ^3.2.0
  lints: ^5.0.0
  test: ^1.24.0
