publish_to: none

name: di
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # Add local dependencies here.
  data:
    path: ../data
  domain:
    path: ../domain
  common:
    path: ../common

  # Add third-party dependencies here.
  dio: ^5.8.0+1
  get_it: ^8.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
